server.port=7999
spring.application.name=config-server

# Enable native profile to read from local file system
spring.profiles.active=native
# Define the folder path where your .properties files will live
spring.cloud.config.server.native.search-locations=file:///C:/Users/2485070/Desktop/config-repo

# Register with Eureka so other services can find it
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/